<?php
  $lang = array(

    //Header
      "home" => "Home",
      "about" => "About",
      "beforeandafter" => "Before and After",
      "contactus" => "Contact Us",
      "myaccount" => "My Account",
      "properties" => "Properties",
      "searchproperties" => "Search Properties",
      "searchproperty" => "Search Property",
      "type" => "Type",
      "category" => "Category",
      "country" => "Country",
      "region" => "Region",
      "bd" => "Bedrooms",
      "br" => "Bathrooms",
      "priceMin" => "Minimum Price",
      "priceMax" => "Maximum Price",
      "features" => "Features",
      "city" => "City",
      "alltypes" => "All types",
      "flat" => "Flat",
      "house" => "House",
      "allcategories" => "All Categories",
      "forrentshort" => "For rent - Short term",
      "forrentlong" => "For rent - Long term",
      "forsale" => "For Sale",
      "allcountries" => "All Countries",
      "allcities" => "All Cities",
      "allregions" => "All Regions",
      "any" => "Any",
      "parking" => "Parking",
      "heating" => "Heating",
      "furniture" => "Furniture",
      "editprofile" => "Edit Profile",
      "editwebsite" => "Edit Website",
      "logout" => "Logout",
      "language" =>"Language",
      "english" => "English",
      "greek" => "Greek",
      "favorites"=> "Favorites",
      "login" => "Login",
      "Register" => "Register",

      //Footer
      "fparagraph" => "Send us an e-mail or phone us to resolve any problem you may ecounter.",
      "fphone" => "Phone:",
      "downloadapp" => "Download our app here!",
      "thecompany" => "The Company",
      "privacypolicy" => "Privacy Policy",
      "tos" => "Terms of Service",
      "fnewsletter" => "Subscribe to our newsletter!",
      "subscriptionsuccess" => "You have been subscribed succesfully. Thank you!",
      "finduson" => "Find us on:",
      "fsubscribe" => "Subscribe",
      "help" => "Help",

      //About
      "atitle" => "Find your next home through us",
      "ahomepage" => "Home",
      "acompany" => "About",
      "since" => "Since 2017",
      "companymessage" => "Short message from us.",
      "amessage" => "Our company is active in the real estate sector in Greece and Cyprus looking for the best possible quality combined with the best price. At the same time, our team is constantly working in order to provide you with updated information regarding the apartments of your choice, taking seriously the criteria that you set yourself. We also undertake renovations, partial or total, decorations, but also the design of smart homes, as well as rentals. Finally, our team will support you in all the required procedures from the very first moment, as well as in securing the required certifications. Look right, invest smart…",
      "athanks" => "Thank you for your trust.",

      //Contact us
      "ccontact" => "Contact Us",
      "contactparagraph" => "Need help? Leave your message down below or send us an Email. Also you can message us to our socia media. We would love to help you out!",
      "chome" => "Home",
      "csubject" => "Enter subject",
      "cmessage" => "Please login in order to send us a message about any inquiry you may have.",
      "ctext" => "Leave us a message and we will get back to you as soon as possible!",
      "cbutton" => "Send Message",
      "sayhello" => "Say Hello",
      "csocial" => "Social Networks",

      //Edit profile
      "forgotpassword" => "Forgot Passsword?",
      "register" => "Register",
      "firstname" => "First name",
      "lastname" => "Last name",
      "phone" => "Phone number",
      "chpassword" => "Change password",
      "cupassword" => "Current password",
      "npassword" => "New password",
      "confirm" => "Confirm",
      "password" => "password",
      "keepintouch" => "Keep in Touch",
      "emailnotifications" => "Email Notifications",
      "newsletter" => "Newsletter",
      "savechanges" => "Save Changes",
      

      //Login
      "deleteaccount" => "Delete Account?",
      "cancel" => "Cancel",
      "login" => "Login",
      "wronglogin" => "This user does not exist.",
      "wrongpass" => "The password you have entered is incorrect.",
      "stmfail" => "Something went wrong. Please try again.",
      
      //Home page
      "services" => "Our Services",
      "rl" => "Rent long-term",
      "rh" => "Rent your next home.",
      "rs" => "Rent short-term",
      "pi1" => "Buy your next home for vacation or short term stay.",
      "buy" => "Buy",
      "pi2" => "Buy your next home.",
      "pi3" => "Renovated Homes.",
      "reno" => "Renovations",

      //Property Single and Renovation Single
      "pshome" => "Home",
      "psproperties" => "Properties",
      "propertyno" => "Property no",
      "prdescription" => "Description",
      "prsummary" => "Quick Summary",
      "prsamenities" => "Amenities",
      "prcontact" => "Contact",
      "prcompany" => "The Company",
      "prmessage" => "Please login to send a message about this property.",
      "propertyid" => "Property ID:",
      "propertylocation" => "Location:",
      "propertytype" => "Property Type:",
      "propertystatus" => "Status:",
      "propertybedrooms" => "Bedrooms:",
      "propertybathrooms" => "Bathrooms:",
      "propertyparking" => "Parking:",
      "propertyfurniture" => "Furniture:",
      "propertyheating" => "Heating System:",
      "propertyfloors" => "Floors:",
      "propertydoc" => "Construction Date:",
      "propertyaf" => "Available From:",
      "propertyarea" => "Area:",
      "propertypps" => "Price/m<sup>2</sup>:",
      "propertyfavs" => "Add to Favorites:",
      "propertyshare" => "Share:",
      "propertyvideo" => "Video",
      "propertylc" => "Location",
      "propertyvt" => "Virtual Tour",

      //Property Grid and Renovation Grid
      "pgourproperties" => "Our Properties",
      "pghome" => "Home",
      "pghproperty" => "Properties Grid",
      "pgclick" => "Click here to view",
      "pgsqm" => "k/m<sup>2</sup>",

      //Renovation extras
      "rrenovations" => "Renovations",
      "rrenovationsgrid" => "Renovation Grid",
      "renovationID" => "Renovations",
      "renono" => "Renovation no.",
      "before" => "Before",
      "after" => "After",
      "videobefore" => "Video Before",
      "videoafter" => "Video After",

      //Favorites
      "favorites"=>"Favorites",
      "deletefavorites" =>"Delete from favorites",
      "click" =>"Click Here"
  );
